In [1]:
#importar as bibliotecas 
from numpy import pi
from numpy import sys
import numpy as np

In [2]:
print('Versão atual do numpy', np.__version__)

Versão atual do numpy 1.18.5


In [7]:
#Criar instancia de gerador de numeros aleatorios padrão
rg = np.random.default_rng(1)
a = np.floor(10 * rg.random((3, 4)))
a


array([[5., 9., 1., 9.],
       [3., 4., 8., 4.],
       [5., 0., 7., 5.]])

In [8]:
a.shape

(3, 4)

In [9]:
#Retorna em array
a.ravel()

array([5., 9., 1., 9., 3., 4., 8., 4., 5., 0., 7., 5.])

In [10]:
#Retorna modificado
a.reshape(6, 2)

array([[5., 9.],
       [1., 9.],
       [3., 4.],
       [8., 4.],
       [5., 0.],
       [7., 5.]])

In [11]:
#Retorna transposta
a.T

array([[5., 3., 5.],
       [9., 4., 0.],
       [1., 8., 7.],
       [9., 4., 5.]])

In [12]:
a.T.shape

(4, 3)

In [13]:
a

array([[5., 9., 1., 9.],
       [3., 4., 8., 4.],
       [5., 0., 7., 5.]])

In [14]:
a.resize((2, 6))
a

array([[5., 9., 1., 9., 3., 4.],
       [8., 4., 5., 0., 7., 5.]])

In [15]:
a.reshape(3, -1)

array([[5., 9., 1., 9.],
       [3., 4., 8., 4.],
       [5., 0., 7., 5.]])